baseURL = 'https://harljo.uk/'
languageCode = 'en-us'
title = "Harley's Blog"
theme = "PaperMod"

[params]
  # Appearance
  defaultTheme = "auto"                     # auto, light, dark
  disableThemeToggle = false                # Enable/disable theme toggle
  color = 'linen'                           # linen, wheat, gray, light

  # Home Info
  ShowReadingTime = true
  ShowShareButtons = true
  ShowToc = true
  comments = false
  ShowBreadCrumbs = true
  ShowPostNavLinks = false
  ShowCodeCopyButtons = true
  ShowWordCount = true
  UseHugoToc = true

  [params.homeInfo]
    Title = "Harley"
    Content = "I am a technologist who likes yapping about social media protocols."

    [[params.social]]
      icon = "github"
      icon_pack = "fab"
      url = "https://github.com/HarlJo"
      name = "GitHub"

    [[params.social]]
      icon = "instagram"
      icon_pack = "fab"
      url = "https://instagram.com/itsharljo"
      name = "Instagram"

    [[params.social]]
      icon = "mastodon"
      icon_pack = "fab"
      url = "https://fosstodon.org/@hcj"
      name = "Mastodon"

    [[params.social]]
      icon = "threads"
      icon_pack = "custom"
      url = "https://threads.net/@itsharljo"
      name = "Threads"

    [[params.social]]
      icon = "bluesky"
      icon_pack = "custom"
      url = "https://bsky.app/profile/harljo.uk"
      name = "Bluesky"

    [[params.social]]
      icon = "rss"
      icon_pack = "fas"
      url = "/index.xml"
      name = "RSS Feed"



  # Miscellaneous
  disableHLJS = true                        # Disable highlight.js
  monoDarkIcon = true                       # Use monochrome dark mode icon
  math = true                               # Enable KaTeX math rendering
  localKatex = false                        # Use local KaTeX instead of CDN

  # Favicon
  favicon = "/favicon.ico"
  appleTouchIcon = "/favicons/apple-touch-icon.png"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  # [[menu.main]]
    # name = "About"
    # url = "/about/"
    # weight = 3
  [[menu.main]]
    name = "Python IDE"
    url = "/ide/"
    weight = 4
