baseURL = 'https://harljo.uk/'
languageCode = 'en-us'
title = "Harley's Blog"
theme = "PaperMod"

[params]
  # Appearance
  defaultTheme = "auto"                     # auto, light, dark
  disableThemeToggle = false                # Enable/disable theme toggle
  color = 'linen'                           # linen, wheat, gray, light

  # Home Info
  ShowReadingTime = true
  ShowShareButtons = true
  ShowToc = true
  comments = false
  ShowBreadCrumbs = true
  ShowPostNavLinks = false
  ShowCodeCopyButtons = true
  ShowWordCount = true
  UseHugoToc = true

  [params.homeInfo]
    Title = "Harley"
    Content = "I am a technologist who likes yapping about social media protocols."

  # Social Icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/HarlJo"
  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/itsharljo"
  [[params.socialIcons]]
    name = "mastodon"
    url = "https://fosstodon.org/@hcj"
  [[params.socialIcons]]
    name = "threads"
    url = "https://threads.net/@itsharljo"
  [[params.socialIcons]]
    name = "bluesky"
    url = "https://bsky.app/profile/harljo.uk"
  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

  # Miscellaneous
  disableHLJS = true                        # Disable highlight.js
  monoDarkIcon = true                       # Use monochrome dark mode icon
  math = true                               # Enable KaTeX math rendering
  localKatex = false                        # Use local KaTeX instead of CDN

  # Favicon
  favicon = "favicon.ico"
  appleTouchIcon = "apple-touch-icon.png"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  # [[menu.main]]
    # name = "About"
    # url = "/about/"
    # weight = 3
  [[menu.main]]
    name = "Python IDE"
    url = "/ide/"
    weight = 4
